// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package txwatcher

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTransactionNotifierMock creates a new instance of TransactionNotifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionNotifierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionNotifierMock {
	mock := &TransactionNotifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TransactionNotifierMock is an autogenerated mock type for the TransactionNotifier type
type TransactionNotifierMock struct {
	mock.Mock
}

type TransactionNotifierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionNotifierMock) EXPECT() *TransactionNotifierMock_Expecter {
	return &TransactionNotifierMock_Expecter{mock: &_m.Mock}
}

// NotifyTransactions provides a mock function for the type TransactionNotifierMock
func (_mock *TransactionNotifierMock) NotifyTransactions(ctx context.Context, network string, wallet string, txs []Transaction) error {
	ret := _mock.Called(ctx, network, wallet, txs)

	if len(ret) == 0 {
		panic("no return value specified for NotifyTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []Transaction) error); ok {
		r0 = returnFunc(ctx, network, wallet, txs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TransactionNotifierMock_NotifyTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyTransactions'
type TransactionNotifierMock_NotifyTransactions_Call struct {
	*mock.Call
}

// NotifyTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - wallet string
//   - txs []Transaction
func (_e *TransactionNotifierMock_Expecter) NotifyTransactions(ctx interface{}, network interface{}, wallet interface{}, txs interface{}) *TransactionNotifierMock_NotifyTransactions_Call {
	return &TransactionNotifierMock_NotifyTransactions_Call{Call: _e.mock.On("NotifyTransactions", ctx, network, wallet, txs)}
}

func (_c *TransactionNotifierMock_NotifyTransactions_Call) Run(run func(ctx context.Context, network string, wallet string, txs []Transaction)) *TransactionNotifierMock_NotifyTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []Transaction
		if args[3] != nil {
			arg3 = args[3].([]Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TransactionNotifierMock_NotifyTransactions_Call) Return(err error) *TransactionNotifierMock_NotifyTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TransactionNotifierMock_NotifyTransactions_Call) RunAndReturn(run func(ctx context.Context, network string, wallet string, txs []Transaction) error) *TransactionNotifierMock_NotifyTransactions_Call {
	_c.Call.Return(run)
	return _c
}
