// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: walletregistry.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteMonitoredWalletByAddress = `-- name: DeleteMonitoredWalletByAddress :execrows
DELETE FROM "monitored_wallets"
WHERE "network" = $1 AND "address" = $2
`

type DeleteMonitoredWalletByAddressParams struct {
	Network string
	Address string
}

// DeleteMonitoredWalletByAddress
//
//	DELETE FROM "monitored_wallets"
//	WHERE "network" = $1 AND "address" = $2
func (q *Queries) DeleteMonitoredWalletByAddress(ctx context.Context, arg DeleteMonitoredWalletByAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitoredWalletByAddress, arg.Network, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMonitoredWallet = `-- name: InsertMonitoredWallet :exec
INSERT INTO "monitored_wallets" ("id", "network", "address")
VALUES ($1, $2, $3)
`

type InsertMonitoredWalletParams struct {
	ID      uuid.UUID
	Network string
	Address string
}

// InsertMonitoredWallet
//
//	INSERT INTO "monitored_wallets" ("id", "network", "address")
//	VALUES ($1, $2, $3)
func (q *Queries) InsertMonitoredWallet(ctx context.Context, arg InsertMonitoredWalletParams) error {
	_, err := q.db.Exec(ctx, insertMonitoredWallet, arg.ID, arg.Network, arg.Address)
	return err
}
