_anchors:
  default-config: &default-config
    dir: '{{.InterfaceDir}}/mocks'
    pkgname: 'mocks'
    filename: '{{.InterfaceName | snakecase}}.go'
    structname: '{{.InterfaceName}}'

  in-package-config: &in-package-config
    <<: *default-config
    dir: '{{.InterfaceDir}}'
    pkgname: '{{.SrcPackageName}}'
    filename: '{{.InterfaceName | snakecase}}_mock_test.go'
    structname: '{{.InterfaceName}}{{.Mock}}'

all: true
recursive: true
force-file-write: true

packages:
  github.com/gabapcia/blockwatch:
    config: *default-config
  github.com/gabapcia/blockwatch/internal/chainwatch:
    config: *in-package-config
    interfaces:
      Service:
        config: *default-config
  github.com/gabapcia/blockwatch/internal/blockproc:
    config: *in-package-config
    interfaces:
      Service:
        config: *default-config
