all: false
force-file-write: true
packages:
  github.com/gabapcia/blockwatch:
    config:
      all: true
      recursive: true
      dir: '{{.InterfaceDir}}/mocks'
      filename: "{{.InterfaceName | snakecase}}.go"
      pkgname: 'mocks'
      structname: '{{.InterfaceName}}'
