// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chainstream_checkpoint.sql

package chainstreamcheckpoint

import (
	"context"

	"github.com/google/uuid"
)

const getLatestCheckpointByNetwork = `-- name: GetLatestCheckpointByNetwork :one
SELECT c."height"
FROM "chainstream_checkpoint" c
WHERE
    c."network" = UPPER($1)
ORDER BY
    c."height" DESC
LIMIT 1
`

// GetLatestCheckpointByNetwork
//
//	SELECT c."height"
//	FROM "chainstream_checkpoint" c
//	WHERE
//	    c."network" = UPPER($1)
//	ORDER BY
//	    c."height" DESC
//	LIMIT 1
func (q *Queries) GetLatestCheckpointByNetwork(ctx context.Context, network interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestCheckpointByNetwork, network)
	var height int64
	err := row.Scan(&height)
	return height, err
}

const insertCheckpointIfNotExists = `-- name: InsertCheckpointIfNotExists :exec
INSERT INTO "chainstream_checkpoint" ("id", "network", "height")
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT "chainstream_checkpoint_unique" DO NOTHING
`

type InsertCheckpointIfNotExistsParams struct {
	ID      uuid.UUID
	Network string
	Height  int64
}

// InsertCheckpointIfNotExists
//
//	INSERT INTO "chainstream_checkpoint" ("id", "network", "height")
//	VALUES ($1, $2, $3)
//	ON CONFLICT ON CONSTRAINT "chainstream_checkpoint_unique" DO NOTHING
func (q *Queries) InsertCheckpointIfNotExists(ctx context.Context, arg InsertCheckpointIfNotExistsParams) error {
	_, err := q.db.Exec(ctx, insertCheckpointIfNotExists, arg.ID, arg.Network, arg.Height)
	return err
}
