// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package walletregistry

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWalletStorageMock creates a new instance of WalletStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletStorageMock {
	mock := &WalletStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WalletStorageMock is an autogenerated mock type for the WalletStorage type
type WalletStorageMock struct {
	mock.Mock
}

type WalletStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletStorageMock) EXPECT() *WalletStorageMock_Expecter {
	return &WalletStorageMock_Expecter{mock: &_m.Mock}
}

// RegisterWallet provides a mock function for the type WalletStorageMock
func (_mock *WalletStorageMock) RegisterWallet(ctx context.Context, id WalletIdentifier) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWallet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, WalletIdentifier) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WalletStorageMock_RegisterWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWallet'
type WalletStorageMock_RegisterWallet_Call struct {
	*mock.Call
}

// RegisterWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id WalletIdentifier
func (_e *WalletStorageMock_Expecter) RegisterWallet(ctx interface{}, id interface{}) *WalletStorageMock_RegisterWallet_Call {
	return &WalletStorageMock_RegisterWallet_Call{Call: _e.mock.On("RegisterWallet", ctx, id)}
}

func (_c *WalletStorageMock_RegisterWallet_Call) Run(run func(ctx context.Context, id WalletIdentifier)) *WalletStorageMock_RegisterWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 WalletIdentifier
		if args[1] != nil {
			arg1 = args[1].(WalletIdentifier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WalletStorageMock_RegisterWallet_Call) Return(err error) *WalletStorageMock_RegisterWallet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WalletStorageMock_RegisterWallet_Call) RunAndReturn(run func(ctx context.Context, id WalletIdentifier) error) *WalletStorageMock_RegisterWallet_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterWallet provides a mock function for the type WalletStorageMock
func (_mock *WalletStorageMock) UnregisterWallet(ctx context.Context, id WalletIdentifier) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterWallet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, WalletIdentifier) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WalletStorageMock_UnregisterWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterWallet'
type WalletStorageMock_UnregisterWallet_Call struct {
	*mock.Call
}

// UnregisterWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id WalletIdentifier
func (_e *WalletStorageMock_Expecter) UnregisterWallet(ctx interface{}, id interface{}) *WalletStorageMock_UnregisterWallet_Call {
	return &WalletStorageMock_UnregisterWallet_Call{Call: _e.mock.On("UnregisterWallet", ctx, id)}
}

func (_c *WalletStorageMock_UnregisterWallet_Call) Run(run func(ctx context.Context, id WalletIdentifier)) *WalletStorageMock_UnregisterWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 WalletIdentifier
		if args[1] != nil {
			arg1 = args[1].(WalletIdentifier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WalletStorageMock_UnregisterWallet_Call) Return(err error) *WalletStorageMock_UnregisterWallet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WalletStorageMock_UnregisterWallet_Call) RunAndReturn(run func(ctx context.Context, id WalletIdentifier) error) *WalletStorageMock_UnregisterWallet_Call {
	_c.Call.Return(run)
	return _c
}
