// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gabapcia/blockwatch/internal/chainstream"
	mock "github.com/stretchr/testify/mock"
)

// NewChainstreamDispatchFailureNotifier creates a new instance of ChainstreamDispatchFailureNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChainstreamDispatchFailureNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChainstreamDispatchFailureNotifier {
	mock := &ChainstreamDispatchFailureNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChainstreamDispatchFailureNotifier is an autogenerated mock type for the ChainstreamDispatchFailureNotifier type
type ChainstreamDispatchFailureNotifier struct {
	mock.Mock
}

type ChainstreamDispatchFailureNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *ChainstreamDispatchFailureNotifier) EXPECT() *ChainstreamDispatchFailureNotifier_Expecter {
	return &ChainstreamDispatchFailureNotifier_Expecter{mock: &_m.Mock}
}

// NotifyDispatchFailure provides a mock function for the type ChainstreamDispatchFailureNotifier
func (_mock *ChainstreamDispatchFailureNotifier) NotifyDispatchFailure(ctx context.Context, failure chainstream.BlockDispatchFailure) error {
	ret := _mock.Called(ctx, failure)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDispatchFailure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chainstream.BlockDispatchFailure) error); ok {
		r0 = returnFunc(ctx, failure)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDispatchFailure'
type ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call struct {
	*mock.Call
}

// NotifyDispatchFailure is a helper method to define mock.On call
//   - ctx context.Context
//   - failure chainstream.BlockDispatchFailure
func (_e *ChainstreamDispatchFailureNotifier_Expecter) NotifyDispatchFailure(ctx interface{}, failure interface{}) *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call {
	return &ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call{Call: _e.mock.On("NotifyDispatchFailure", ctx, failure)}
}

func (_c *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call) Run(run func(ctx context.Context, failure chainstream.BlockDispatchFailure)) *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chainstream.BlockDispatchFailure
		if args[1] != nil {
			arg1 = args[1].(chainstream.BlockDispatchFailure)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call) Return(err error) *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call) RunAndReturn(run func(ctx context.Context, failure chainstream.BlockDispatchFailure) error) *ChainstreamDispatchFailureNotifier_NotifyDispatchFailure_Call {
	_c.Call.Return(run)
	return _c
}
