// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gabapcia/blockwatch/internal/chainstream"
	"github.com/gabapcia/blockwatch/internal/walletwatch"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// AsChainstreamDispatchFailureNotifier provides a mock function for the type Client
func (_mock *Client) AsChainstreamDispatchFailureNotifier(stream string) chainstream.DispatchFailureNotifier {
	ret := _mock.Called(stream)

	if len(ret) == 0 {
		panic("no return value specified for AsChainstreamDispatchFailureNotifier")
	}

	var r0 chainstream.DispatchFailureNotifier
	if returnFunc, ok := ret.Get(0).(func(string) chainstream.DispatchFailureNotifier); ok {
		r0 = returnFunc(stream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chainstream.DispatchFailureNotifier)
		}
	}
	return r0
}

// Client_AsChainstreamDispatchFailureNotifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsChainstreamDispatchFailureNotifier'
type Client_AsChainstreamDispatchFailureNotifier_Call struct {
	*mock.Call
}

// AsChainstreamDispatchFailureNotifier is a helper method to define mock.On call
//   - stream string
func (_e *Client_Expecter) AsChainstreamDispatchFailureNotifier(stream interface{}) *Client_AsChainstreamDispatchFailureNotifier_Call {
	return &Client_AsChainstreamDispatchFailureNotifier_Call{Call: _e.mock.On("AsChainstreamDispatchFailureNotifier", stream)}
}

func (_c *Client_AsChainstreamDispatchFailureNotifier_Call) Run(run func(stream string)) *Client_AsChainstreamDispatchFailureNotifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_AsChainstreamDispatchFailureNotifier_Call) Return(dispatchFailureNotifier chainstream.DispatchFailureNotifier) *Client_AsChainstreamDispatchFailureNotifier_Call {
	_c.Call.Return(dispatchFailureNotifier)
	return _c
}

func (_c *Client_AsChainstreamDispatchFailureNotifier_Call) RunAndReturn(run func(stream string) chainstream.DispatchFailureNotifier) *Client_AsChainstreamDispatchFailureNotifier_Call {
	_c.Call.Return(run)
	return _c
}

// AsWalletwatchTransactionNotifier provides a mock function for the type Client
func (_mock *Client) AsWalletwatchTransactionNotifier(stream string) walletwatch.TransactionNotifier {
	ret := _mock.Called(stream)

	if len(ret) == 0 {
		panic("no return value specified for AsWalletwatchTransactionNotifier")
	}

	var r0 walletwatch.TransactionNotifier
	if returnFunc, ok := ret.Get(0).(func(string) walletwatch.TransactionNotifier); ok {
		r0 = returnFunc(stream)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(walletwatch.TransactionNotifier)
		}
	}
	return r0
}

// Client_AsWalletwatchTransactionNotifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsWalletwatchTransactionNotifier'
type Client_AsWalletwatchTransactionNotifier_Call struct {
	*mock.Call
}

// AsWalletwatchTransactionNotifier is a helper method to define mock.On call
//   - stream string
func (_e *Client_Expecter) AsWalletwatchTransactionNotifier(stream interface{}) *Client_AsWalletwatchTransactionNotifier_Call {
	return &Client_AsWalletwatchTransactionNotifier_Call{Call: _e.mock.On("AsWalletwatchTransactionNotifier", stream)}
}

func (_c *Client_AsWalletwatchTransactionNotifier_Call) Run(run func(stream string)) *Client_AsWalletwatchTransactionNotifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_AsWalletwatchTransactionNotifier_Call) Return(transactionNotifier walletwatch.TransactionNotifier) *Client_AsWalletwatchTransactionNotifier_Call {
	_c.Call.Return(transactionNotifier)
	return _c
}

func (_c *Client_AsWalletwatchTransactionNotifier_Call) RunAndReturn(run func(stream string) walletwatch.TransactionNotifier) *Client_AsWalletwatchTransactionNotifier_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Client
func (_mock *Client) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(err error) *Client_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}
