// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gabapcia/blockwatch/internal/walletwatch"
	mock "github.com/stretchr/testify/mock"
)

// NewWalletwatchTransactionNotifier creates a new instance of WalletwatchTransactionNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletwatchTransactionNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletwatchTransactionNotifier {
	mock := &WalletwatchTransactionNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WalletwatchTransactionNotifier is an autogenerated mock type for the WalletwatchTransactionNotifier type
type WalletwatchTransactionNotifier struct {
	mock.Mock
}

type WalletwatchTransactionNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletwatchTransactionNotifier) EXPECT() *WalletwatchTransactionNotifier_Expecter {
	return &WalletwatchTransactionNotifier_Expecter{mock: &_m.Mock}
}

// NotifyTransactions provides a mock function for the type WalletwatchTransactionNotifier
func (_mock *WalletwatchTransactionNotifier) NotifyTransactions(ctx context.Context, network string, wallet string, txs []walletwatch.Transaction) error {
	ret := _mock.Called(ctx, network, wallet, txs)

	if len(ret) == 0 {
		panic("no return value specified for NotifyTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []walletwatch.Transaction) error); ok {
		r0 = returnFunc(ctx, network, wallet, txs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WalletwatchTransactionNotifier_NotifyTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyTransactions'
type WalletwatchTransactionNotifier_NotifyTransactions_Call struct {
	*mock.Call
}

// NotifyTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - wallet string
//   - txs []walletwatch.Transaction
func (_e *WalletwatchTransactionNotifier_Expecter) NotifyTransactions(ctx interface{}, network interface{}, wallet interface{}, txs interface{}) *WalletwatchTransactionNotifier_NotifyTransactions_Call {
	return &WalletwatchTransactionNotifier_NotifyTransactions_Call{Call: _e.mock.On("NotifyTransactions", ctx, network, wallet, txs)}
}

func (_c *WalletwatchTransactionNotifier_NotifyTransactions_Call) Run(run func(ctx context.Context, network string, wallet string, txs []walletwatch.Transaction)) *WalletwatchTransactionNotifier_NotifyTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []walletwatch.Transaction
		if args[3] != nil {
			arg3 = args[3].([]walletwatch.Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WalletwatchTransactionNotifier_NotifyTransactions_Call) Return(err error) *WalletwatchTransactionNotifier_NotifyTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WalletwatchTransactionNotifier_NotifyTransactions_Call) RunAndReturn(run func(ctx context.Context, network string, wallet string, txs []walletwatch.Transaction) error) *WalletwatchTransactionNotifier_NotifyTransactions_Call {
	_c.Call.Return(run)
	return _c
}
