package postgresql

import (
	"context"
	"io"

	"github.com/gabapcia/blockwatch/internal/infra/storage/postgresql/querier/chainstreamcheckpoint"
	"github.com/gabapcia/blockwatch/internal/infra/storage/postgresql/querier/monitoredwallets"
	"github.com/gabapcia/blockwatch/internal/infra/storage/postgresql/querier/walletwatchidempotency"

	"github.com/jackc/pgx/v5/pgxpool"
)

// client provides access to PostgreSQL-based implementations of internal storage interfaces.
//
// It wraps a pgx connection pool and exposes strongly typed query sets
// generated by sqlc for each subdomain (walletwatch, chainstream, etc).
type client struct {
	pool *pgxpool.Pool

	monitoredWallets       *monitoredwallets.Queries
	walletwatchIdempotency *walletwatchidempotency.Queries
	chainstreamCheckpoint  *chainstreamcheckpoint.Queries
}

// Close gracefully shuts down the underlying connection pool.
func (c client) Close() error {
	c.pool.Close()
	return nil
}

// New creates a new PostgreSQL client using the provided DSN.
//
// It initializes a connection pool and binds all available sqlc query sets.
//
// Parameters:
//   - ctx: context used to control initialization timeout/cancelation.
//   - dsn: PostgreSQL connection string.
//
// Returns:
//   - A pointer to the initialized client.
//   - An error if the connection could not be established.
func New(ctx context.Context, dsn string) (*client, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, err
	}

	return &client{
		pool:                   pool,
		monitoredWallets:       monitoredwallets.New(pool),
		walletwatchIdempotency: walletwatchidempotency.New(pool),
		chainstreamCheckpoint:  chainstreamcheckpoint.New(pool),
	}, nil
}

// Compile-time assertion to ensure client implements io.Closer.
var _ io.Closer = new(client)
