// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/gabapcia/blockwatch/internal/pkg/x/types"
	"github.com/gabapcia/blockwatch/internal/walletregistry"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// ClaimBlockForTxWatch provides a mock function for the type Client
func (_mock *Client) ClaimBlockForTxWatch(ctx context.Context, network string, blockHash string, ttl time.Duration) error {
	ret := _mock.Called(ctx, network, blockHash, ttl)

	if len(ret) == 0 {
		panic("no return value specified for ClaimBlockForTxWatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, network, blockHash, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_ClaimBlockForTxWatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimBlockForTxWatch'
type Client_ClaimBlockForTxWatch_Call struct {
	*mock.Call
}

// ClaimBlockForTxWatch is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - blockHash string
//   - ttl time.Duration
func (_e *Client_Expecter) ClaimBlockForTxWatch(ctx interface{}, network interface{}, blockHash interface{}, ttl interface{}) *Client_ClaimBlockForTxWatch_Call {
	return &Client_ClaimBlockForTxWatch_Call{Call: _e.mock.On("ClaimBlockForTxWatch", ctx, network, blockHash, ttl)}
}

func (_c *Client_ClaimBlockForTxWatch_Call) Run(run func(ctx context.Context, network string, blockHash string, ttl time.Duration)) *Client_ClaimBlockForTxWatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_ClaimBlockForTxWatch_Call) Return(err error) *Client_ClaimBlockForTxWatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_ClaimBlockForTxWatch_Call) RunAndReturn(run func(ctx context.Context, network string, blockHash string, ttl time.Duration) error) *Client_ClaimBlockForTxWatch_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Client
func (_mock *Client) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(err error) *Client_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// FilterWatchedWallets provides a mock function for the type Client
func (_mock *Client) FilterWatchedWallets(ctx context.Context, network string, addresses []string) ([]string, error) {
	ret := _mock.Called(ctx, network, addresses)

	if len(ret) == 0 {
		panic("no return value specified for FilterWatchedWallets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, error)); ok {
		return returnFunc(ctx, network, addresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, network, addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, network, addresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_FilterWatchedWallets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterWatchedWallets'
type Client_FilterWatchedWallets_Call struct {
	*mock.Call
}

// FilterWatchedWallets is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - addresses []string
func (_e *Client_Expecter) FilterWatchedWallets(ctx interface{}, network interface{}, addresses interface{}) *Client_FilterWatchedWallets_Call {
	return &Client_FilterWatchedWallets_Call{Call: _e.mock.On("FilterWatchedWallets", ctx, network, addresses)}
}

func (_c *Client_FilterWatchedWallets_Call) Run(run func(ctx context.Context, network string, addresses []string)) *Client_FilterWatchedWallets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_FilterWatchedWallets_Call) Return(strings []string, err error) *Client_FilterWatchedWallets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Client_FilterWatchedWallets_Call) RunAndReturn(run func(ctx context.Context, network string, addresses []string) ([]string, error)) *Client_FilterWatchedWallets_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLatestCheckpoint provides a mock function for the type Client
func (_mock *Client) LoadLatestCheckpoint(ctx context.Context, network string) (types.Hex, error) {
	ret := _mock.Called(ctx, network)

	if len(ret) == 0 {
		panic("no return value specified for LoadLatestCheckpoint")
	}

	var r0 types.Hex
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Hex, error)); ok {
		return returnFunc(ctx, network)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Hex); ok {
		r0 = returnFunc(ctx, network)
	} else {
		r0 = ret.Get(0).(types.Hex)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, network)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_LoadLatestCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLatestCheckpoint'
type Client_LoadLatestCheckpoint_Call struct {
	*mock.Call
}

// LoadLatestCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
func (_e *Client_Expecter) LoadLatestCheckpoint(ctx interface{}, network interface{}) *Client_LoadLatestCheckpoint_Call {
	return &Client_LoadLatestCheckpoint_Call{Call: _e.mock.On("LoadLatestCheckpoint", ctx, network)}
}

func (_c *Client_LoadLatestCheckpoint_Call) Run(run func(ctx context.Context, network string)) *Client_LoadLatestCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_LoadLatestCheckpoint_Call) Return(hex types.Hex, err error) *Client_LoadLatestCheckpoint_Call {
	_c.Call.Return(hex, err)
	return _c
}

func (_c *Client_LoadLatestCheckpoint_Call) RunAndReturn(run func(ctx context.Context, network string) (types.Hex, error)) *Client_LoadLatestCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBlockTxWatchComplete provides a mock function for the type Client
func (_mock *Client) MarkBlockTxWatchComplete(ctx context.Context, network string, blockHash string) error {
	ret := _mock.Called(ctx, network, blockHash)

	if len(ret) == 0 {
		panic("no return value specified for MarkBlockTxWatchComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, network, blockHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_MarkBlockTxWatchComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBlockTxWatchComplete'
type Client_MarkBlockTxWatchComplete_Call struct {
	*mock.Call
}

// MarkBlockTxWatchComplete is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - blockHash string
func (_e *Client_Expecter) MarkBlockTxWatchComplete(ctx interface{}, network interface{}, blockHash interface{}) *Client_MarkBlockTxWatchComplete_Call {
	return &Client_MarkBlockTxWatchComplete_Call{Call: _e.mock.On("MarkBlockTxWatchComplete", ctx, network, blockHash)}
}

func (_c *Client_MarkBlockTxWatchComplete_Call) Run(run func(ctx context.Context, network string, blockHash string)) *Client_MarkBlockTxWatchComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_MarkBlockTxWatchComplete_Call) Return(err error) *Client_MarkBlockTxWatchComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_MarkBlockTxWatchComplete_Call) RunAndReturn(run func(ctx context.Context, network string, blockHash string) error) *Client_MarkBlockTxWatchComplete_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterWallet provides a mock function for the type Client
func (_mock *Client) RegisterWallet(ctx context.Context, id walletregistry.WalletIdentifier) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RegisterWallet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, walletregistry.WalletIdentifier) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_RegisterWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWallet'
type Client_RegisterWallet_Call struct {
	*mock.Call
}

// RegisterWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id walletregistry.WalletIdentifier
func (_e *Client_Expecter) RegisterWallet(ctx interface{}, id interface{}) *Client_RegisterWallet_Call {
	return &Client_RegisterWallet_Call{Call: _e.mock.On("RegisterWallet", ctx, id)}
}

func (_c *Client_RegisterWallet_Call) Run(run func(ctx context.Context, id walletregistry.WalletIdentifier)) *Client_RegisterWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 walletregistry.WalletIdentifier
		if args[1] != nil {
			arg1 = args[1].(walletregistry.WalletIdentifier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_RegisterWallet_Call) Return(err error) *Client_RegisterWallet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_RegisterWallet_Call) RunAndReturn(run func(ctx context.Context, id walletregistry.WalletIdentifier) error) *Client_RegisterWallet_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCheckpoint provides a mock function for the type Client
func (_mock *Client) SaveCheckpoint(ctx context.Context, network string, height types.Hex) error {
	ret := _mock.Called(ctx, network, height)

	if len(ret) == 0 {
		panic("no return value specified for SaveCheckpoint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Hex) error); ok {
		r0 = returnFunc(ctx, network, height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_SaveCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCheckpoint'
type Client_SaveCheckpoint_Call struct {
	*mock.Call
}

// SaveCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - height types.Hex
func (_e *Client_Expecter) SaveCheckpoint(ctx interface{}, network interface{}, height interface{}) *Client_SaveCheckpoint_Call {
	return &Client_SaveCheckpoint_Call{Call: _e.mock.On("SaveCheckpoint", ctx, network, height)}
}

func (_c *Client_SaveCheckpoint_Call) Run(run func(ctx context.Context, network string, height types.Hex)) *Client_SaveCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Hex
		if args[2] != nil {
			arg2 = args[2].(types.Hex)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_SaveCheckpoint_Call) Return(err error) *Client_SaveCheckpoint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_SaveCheckpoint_Call) RunAndReturn(run func(ctx context.Context, network string, height types.Hex) error) *Client_SaveCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterWallet provides a mock function for the type Client
func (_mock *Client) UnregisterWallet(ctx context.Context, id walletregistry.WalletIdentifier) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterWallet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, walletregistry.WalletIdentifier) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UnregisterWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterWallet'
type Client_UnregisterWallet_Call struct {
	*mock.Call
}

// UnregisterWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - id walletregistry.WalletIdentifier
func (_e *Client_Expecter) UnregisterWallet(ctx interface{}, id interface{}) *Client_UnregisterWallet_Call {
	return &Client_UnregisterWallet_Call{Call: _e.mock.On("UnregisterWallet", ctx, id)}
}

func (_c *Client_UnregisterWallet_Call) Run(run func(ctx context.Context, id walletregistry.WalletIdentifier)) *Client_UnregisterWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 walletregistry.WalletIdentifier
		if args[1] != nil {
			arg1 = args[1].(walletregistry.WalletIdentifier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_UnregisterWallet_Call) Return(err error) *Client_UnregisterWallet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UnregisterWallet_Call) RunAndReturn(run func(ctx context.Context, id walletregistry.WalletIdentifier) error) *Client_UnregisterWallet_Call {
	_c.Call.Return(run)
	return _c
}
