// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package querier

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores wallets being monitored by network and address
type MonitoredWallet struct {
	// Timestamp when the wallet was registered
	CreatedAt pgtype.Timestamptz
	// Unique identifier for the monitored wallet
	ID uuid.UUID
	// Blockchain network name in uppercase (e.g., ETHEREUM)
	Network string
	// Wallet address being monitored
	Address string
}
