// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: monitored_wallets.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const deleteMonitoredWalletByAddress = `-- name: DeleteMonitoredWalletByAddress :execrows
DELETE FROM "monitored_wallets"
WHERE "network" = UPPER($1) AND "address" = $2
`

type DeleteMonitoredWalletByAddressParams struct {
	Network interface{}
	Address string
}

// DeleteMonitoredWalletByAddress
//
//	DELETE FROM "monitored_wallets"
//	WHERE "network" = UPPER($1) AND "address" = $2
func (q *Queries) DeleteMonitoredWalletByAddress(ctx context.Context, arg DeleteMonitoredWalletByAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMonitoredWalletByAddress, arg.Network, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const filterMonitoredWallets = `-- name: FilterMonitoredWallets :many
SELECT w."address"
FROM "monitored_wallets" w
WHERE w."network" = UPPER($1) AND w."address" = ANY($2::TEXT[])
`

type FilterMonitoredWalletsParams struct {
	Network   interface{}
	Addresses []string
}

// FilterMonitoredWallets
//
//	SELECT w."address"
//	FROM "monitored_wallets" w
//	WHERE w."network" = UPPER($1) AND w."address" = ANY($2::TEXT[])
func (q *Queries) FilterMonitoredWallets(ctx context.Context, arg FilterMonitoredWalletsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filterMonitoredWallets, arg.Network, arg.Addresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMonitoredWallet = `-- name: InsertMonitoredWallet :exec
INSERT INTO "monitored_wallets" ("id", "network", "address")
VALUES ($1, $2, $3)
`

type InsertMonitoredWalletParams struct {
	ID      uuid.UUID
	Network string
	Address string
}

// InsertMonitoredWallet
//
//	INSERT INTO "monitored_wallets" ("id", "network", "address")
//	VALUES ($1, $2, $3)
func (q *Queries) InsertMonitoredWallet(ctx context.Context, arg InsertMonitoredWalletParams) error {
	_, err := q.db.Exec(ctx, insertMonitoredWallet, arg.ID, arg.Network, arg.Address)
	return err
}
