// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: walletwatch.sql

package querier

import (
	"context"
)

const filterMonitoredWallets = `-- name: FilterMonitoredWallets :many
SELECT w."address"
FROM "monitored_wallets" w
WHERE w."network" = UPPER($1) AND w."address" = ANY($2::TEXT[])
`

type FilterMonitoredWalletsParams struct {
	Network   interface{}
	Addresses []string
}

// FilterMonitoredWallets
//
//	SELECT w."address"
//	FROM "monitored_wallets" w
//	WHERE w."network" = UPPER($1) AND w."address" = ANY($2::TEXT[])
func (q *Queries) FilterMonitoredWallets(ctx context.Context, arg FilterMonitoredWalletsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filterMonitoredWallets, arg.Network, arg.Addresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
