// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: walletwatch_idempotency.sql

package walletwatchidempotency

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimOrExtendIfExpired = `-- name: ClaimOrExtendIfExpired :execrows
INSERT INTO "walletwatch_idempotency" ("id", "network", "block_hash", "in_progress_until")
VALUES ($1, $2, $3, $4)
ON CONFLICT ON CONSTRAINT "walletwatch_idempotency_unique"
DO UPDATE
SET
    "in_progress_until" = EXCLUDED."in_progress_until"
WHERE
    "walletwatch_idempotency"."finished_at" IS NULL AND
    "walletwatch_idempotency"."in_progress_until" < NOW()
`

type ClaimOrExtendIfExpiredParams struct {
	ID              uuid.UUID
	Network         string
	BlockHash       string
	InProgressUntil time.Time
}

// ClaimOrExtendIfExpired
//
//	INSERT INTO "walletwatch_idempotency" ("id", "network", "block_hash", "in_progress_until")
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT ON CONSTRAINT "walletwatch_idempotency_unique"
//	DO UPDATE
//	SET
//	    "in_progress_until" = EXCLUDED."in_progress_until"
//	WHERE
//	    "walletwatch_idempotency"."finished_at" IS NULL AND
//	    "walletwatch_idempotency"."in_progress_until" < NOW()
func (q *Queries) ClaimOrExtendIfExpired(ctx context.Context, arg ClaimOrExtendIfExpiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimOrExtendIfExpired,
		arg.ID,
		arg.Network,
		arg.BlockHash,
		arg.InProgressUntil,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findClaim = `-- name: FindClaim :one
SELECT i.created_at, i.updated_at, i.finished_at, i.id, i.network, i.block_hash, i.in_progress_until
FROM "walletwatch_idempotency" i
WHERE
    i."network" = UPPER($1) AND
    i."block_hash" = $2
`

type FindClaimParams struct {
	Network   interface{}
	BlockHash string
}

// FindClaim
//
//	SELECT i.created_at, i.updated_at, i.finished_at, i.id, i.network, i.block_hash, i.in_progress_until
//	FROM "walletwatch_idempotency" i
//	WHERE
//	    i."network" = UPPER($1) AND
//	    i."block_hash" = $2
func (q *Queries) FindClaim(ctx context.Context, arg FindClaimParams) (WalletwatchIdempotency, error) {
	row := q.db.QueryRow(ctx, findClaim, arg.Network, arg.BlockHash)
	var i WalletwatchIdempotency
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.ID,
		&i.Network,
		&i.BlockHash,
		&i.InProgressUntil,
	)
	return i, err
}

const markClaimAsCompleted = `-- name: MarkClaimAsCompleted :exec
UPDATE "walletwatch_idempotency"
SET
    "finished_at" = NOW()
WHERE
    "network" = UPPER($1) AND
    "block_hash" = $2 AND
    "finished_at" IS NULL
`

type MarkClaimAsCompletedParams struct {
	Network   interface{}
	BlockHash string
}

// MarkClaimAsCompleted
//
//	UPDATE "walletwatch_idempotency"
//	SET
//	    "finished_at" = NOW()
//	WHERE
//	    "network" = UPPER($1) AND
//	    "block_hash" = $2 AND
//	    "finished_at" IS NULL
func (q *Queries) MarkClaimAsCompleted(ctx context.Context, arg MarkClaimAsCompletedParams) error {
	_, err := q.db.Exec(ctx, markClaimAsCompleted, arg.Network, arg.BlockHash)
	return err
}
