// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// StartWatching provides a mock function for the type Service
func (_mock *Service) StartWatching(ctx context.Context, network string, address string) error {
	ret := _mock.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for StartWatching")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, network, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_StartWatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWatching'
type Service_StartWatching_Call struct {
	*mock.Call
}

// StartWatching is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *Service_Expecter) StartWatching(ctx interface{}, network interface{}, address interface{}) *Service_StartWatching_Call {
	return &Service_StartWatching_Call{Call: _e.mock.On("StartWatching", ctx, network, address)}
}

func (_c *Service_StartWatching_Call) Run(run func(ctx context.Context, network string, address string)) *Service_StartWatching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_StartWatching_Call) Return(err error) *Service_StartWatching_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_StartWatching_Call) RunAndReturn(run func(ctx context.Context, network string, address string) error) *Service_StartWatching_Call {
	_c.Call.Return(run)
	return _c
}

// StopWatching provides a mock function for the type Service
func (_mock *Service) StopWatching(ctx context.Context, network string, address string) error {
	ret := _mock.Called(ctx, network, address)

	if len(ret) == 0 {
		panic("no return value specified for StopWatching")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, network, address)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_StopWatching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopWatching'
type Service_StopWatching_Call struct {
	*mock.Call
}

// StopWatching is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - address string
func (_e *Service_Expecter) StopWatching(ctx interface{}, network interface{}, address interface{}) *Service_StopWatching_Call {
	return &Service_StopWatching_Call{Call: _e.mock.On("StopWatching", ctx, network, address)}
}

func (_c *Service_StopWatching_Call) Run(run func(ctx context.Context, network string, address string)) *Service_StopWatching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_StopWatching_Call) Return(err error) *Service_StopWatching_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_StopWatching_Call) RunAndReturn(run func(ctx context.Context, network string, address string) error) *Service_StopWatching_Call {
	_c.Call.Return(run)
	return _c
}
