// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chainstream

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewDispatchFailureNotifierMock creates a new instance of DispatchFailureNotifierMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatchFailureNotifierMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DispatchFailureNotifierMock {
	mock := &DispatchFailureNotifierMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DispatchFailureNotifierMock is an autogenerated mock type for the DispatchFailureNotifier type
type DispatchFailureNotifierMock struct {
	mock.Mock
}

type DispatchFailureNotifierMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DispatchFailureNotifierMock) EXPECT() *DispatchFailureNotifierMock_Expecter {
	return &DispatchFailureNotifierMock_Expecter{mock: &_m.Mock}
}

// NotifyDispatchFailure provides a mock function for the type DispatchFailureNotifierMock
func (_mock *DispatchFailureNotifierMock) NotifyDispatchFailure(ctx context.Context, failure BlockDispatchFailure) error {
	ret := _mock.Called(ctx, failure)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDispatchFailure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BlockDispatchFailure) error); ok {
		r0 = returnFunc(ctx, failure)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DispatchFailureNotifierMock_NotifyDispatchFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDispatchFailure'
type DispatchFailureNotifierMock_NotifyDispatchFailure_Call struct {
	*mock.Call
}

// NotifyDispatchFailure is a helper method to define mock.On call
//   - ctx context.Context
//   - failure BlockDispatchFailure
func (_e *DispatchFailureNotifierMock_Expecter) NotifyDispatchFailure(ctx interface{}, failure interface{}) *DispatchFailureNotifierMock_NotifyDispatchFailure_Call {
	return &DispatchFailureNotifierMock_NotifyDispatchFailure_Call{Call: _e.mock.On("NotifyDispatchFailure", ctx, failure)}
}

func (_c *DispatchFailureNotifierMock_NotifyDispatchFailure_Call) Run(run func(ctx context.Context, failure BlockDispatchFailure)) *DispatchFailureNotifierMock_NotifyDispatchFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BlockDispatchFailure
		if args[1] != nil {
			arg1 = args[1].(BlockDispatchFailure)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DispatchFailureNotifierMock_NotifyDispatchFailure_Call) Return(err error) *DispatchFailureNotifierMock_NotifyDispatchFailure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DispatchFailureNotifierMock_NotifyDispatchFailure_Call) RunAndReturn(run func(ctx context.Context, failure BlockDispatchFailure) error) *DispatchFailureNotifierMock_NotifyDispatchFailure_Call {
	_c.Call.Return(run)
	return _c
}
