// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package walletwatch

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWalletStorageMock creates a new instance of WalletStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletStorageMock {
	mock := &WalletStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WalletStorageMock is an autogenerated mock type for the WalletStorage type
type WalletStorageMock struct {
	mock.Mock
}

type WalletStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletStorageMock) EXPECT() *WalletStorageMock_Expecter {
	return &WalletStorageMock_Expecter{mock: &_m.Mock}
}

// GetTransactionsByWallet provides a mock function for the type WalletStorageMock
func (_mock *WalletStorageMock) GetTransactionsByWallet(ctx context.Context, network string, txs []Transaction) (map[string][]Transaction, error) {
	ret := _mock.Called(ctx, network, txs)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionsByWallet")
	}

	var r0 map[string][]Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []Transaction) (map[string][]Transaction, error)); ok {
		return returnFunc(ctx, network, txs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []Transaction) map[string][]Transaction); ok {
		r0 = returnFunc(ctx, network, txs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []Transaction) error); ok {
		r1 = returnFunc(ctx, network, txs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WalletStorageMock_GetTransactionsByWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionsByWallet'
type WalletStorageMock_GetTransactionsByWallet_Call struct {
	*mock.Call
}

// GetTransactionsByWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - txs []Transaction
func (_e *WalletStorageMock_Expecter) GetTransactionsByWallet(ctx interface{}, network interface{}, txs interface{}) *WalletStorageMock_GetTransactionsByWallet_Call {
	return &WalletStorageMock_GetTransactionsByWallet_Call{Call: _e.mock.On("GetTransactionsByWallet", ctx, network, txs)}
}

func (_c *WalletStorageMock_GetTransactionsByWallet_Call) Run(run func(ctx context.Context, network string, txs []Transaction)) *WalletStorageMock_GetTransactionsByWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []Transaction
		if args[2] != nil {
			arg2 = args[2].([]Transaction)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WalletStorageMock_GetTransactionsByWallet_Call) Return(stringToTransactions map[string][]Transaction, err error) *WalletStorageMock_GetTransactionsByWallet_Call {
	_c.Call.Return(stringToTransactions, err)
	return _c
}

func (_c *WalletStorageMock_GetTransactionsByWallet_Call) RunAndReturn(run func(ctx context.Context, network string, txs []Transaction) (map[string][]Transaction, error)) *WalletStorageMock_GetTransactionsByWallet_Call {
	_c.Call.Return(run)
	return _c
}
