// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package walletwatch

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewWalletStorageMock creates a new instance of WalletStorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletStorageMock {
	mock := &WalletStorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WalletStorageMock is an autogenerated mock type for the WalletStorage type
type WalletStorageMock struct {
	mock.Mock
}

type WalletStorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WalletStorageMock) EXPECT() *WalletStorageMock_Expecter {
	return &WalletStorageMock_Expecter{mock: &_m.Mock}
}

// FilterWatchedWallets provides a mock function for the type WalletStorageMock
func (_mock *WalletStorageMock) FilterWatchedWallets(ctx context.Context, network string, addresses []string) ([]string, error) {
	ret := _mock.Called(ctx, network, addresses)

	if len(ret) == 0 {
		panic("no return value specified for FilterWatchedWallets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]string, error)); ok {
		return returnFunc(ctx, network, addresses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []string); ok {
		r0 = returnFunc(ctx, network, addresses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, network, addresses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WalletStorageMock_FilterWatchedWallets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterWatchedWallets'
type WalletStorageMock_FilterWatchedWallets_Call struct {
	*mock.Call
}

// FilterWatchedWallets is a helper method to define mock.On call
//   - ctx context.Context
//   - network string
//   - addresses []string
func (_e *WalletStorageMock_Expecter) FilterWatchedWallets(ctx interface{}, network interface{}, addresses interface{}) *WalletStorageMock_FilterWatchedWallets_Call {
	return &WalletStorageMock_FilterWatchedWallets_Call{Call: _e.mock.On("FilterWatchedWallets", ctx, network, addresses)}
}

func (_c *WalletStorageMock_FilterWatchedWallets_Call) Run(run func(ctx context.Context, network string, addresses []string)) *WalletStorageMock_FilterWatchedWallets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WalletStorageMock_FilterWatchedWallets_Call) Return(strings []string, err error) *WalletStorageMock_FilterWatchedWallets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *WalletStorageMock_FilterWatchedWallets_Call) RunAndReturn(run func(ctx context.Context, network string, addresses []string) ([]string, error)) *WalletStorageMock_FilterWatchedWallets_Call {
	_c.Call.Return(run)
	return _c
}
