// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package monitoredwallets

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores block height checkpoints per blockchain network for stream processing
type ChainstreamCheckpoint struct {
	// Timestamp when the checkpoint record was inserted
	CreatedAt time.Time
	// Unique UUID identifier for the checkpoint entry
	ID uuid.UUID
	// Blockchain network name (stored in uppercase)
	Network string
	// Block height being tracked as a checkpoint
	Height int64
}

// Stores wallets being monitored by network and address
type MonitoredWallet struct {
	// Timestamp when the wallet was registered
	CreatedAt time.Time
	// Unique identifier for the monitored wallet
	ID uuid.UUID
	// Blockchain network name in uppercase (e.g., ETHEREUM)
	Network string
	// Wallet address being monitored
	Address string
}

// Tracks block processing attempts in walletwatch with TTL-based in-progress logic for idempotency
type WalletwatchIdempotency struct {
	// Timestamp when the record was initially inserted
	CreatedAt time.Time
	// Timestamp of the most recent modification, auto-updated via trigger
	UpdatedAt time.Time
	// Timestamp when block processing finished (optional)
	FinishedAt pgtype.Timestamptz
	// Unique identifier for the idempotency record
	ID uuid.UUID
	// Blockchain network identifier, always stored in uppercase (e.g., ETHEREUM)
	Network string
	// Hash of the block being processed, unique per network
	BlockHash string
	// Deadline until which the processing is considered active (used for TTL and concurrency control)
	InProgressUntil time.Time
}
