// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gabapcia/blockwatch/internal/walletwatch"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// NotifyWatchedTransactions provides a mock function for the type Service
func (_mock *Service) NotifyWatchedTransactions(ctx context.Context, block walletwatch.Block) error {
	ret := _mock.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for NotifyWatchedTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, walletwatch.Block) error); ok {
		r0 = returnFunc(ctx, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_NotifyWatchedTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyWatchedTransactions'
type Service_NotifyWatchedTransactions_Call struct {
	*mock.Call
}

// NotifyWatchedTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - block walletwatch.Block
func (_e *Service_Expecter) NotifyWatchedTransactions(ctx interface{}, block interface{}) *Service_NotifyWatchedTransactions_Call {
	return &Service_NotifyWatchedTransactions_Call{Call: _e.mock.On("NotifyWatchedTransactions", ctx, block)}
}

func (_c *Service_NotifyWatchedTransactions_Call) Run(run func(ctx context.Context, block walletwatch.Block)) *Service_NotifyWatchedTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 walletwatch.Block
		if args[1] != nil {
			arg1 = args[1].(walletwatch.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_NotifyWatchedTransactions_Call) Return(err error) *Service_NotifyWatchedTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_NotifyWatchedTransactions_Call) RunAndReturn(run func(ctx context.Context, block walletwatch.Block) error) *Service_NotifyWatchedTransactions_Call {
	_c.Call.Return(run)
	return _c
}
