name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Start Docker
      run: |
        sudo systemctl start docker
        docker --version

    - name: Run tests
      run: make unit-tests
